/* tslint:disable */
/* eslint-disable */
/**
 * Testplan API
 * API for managing test plans and related resources.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `chrome` - Chrome
 * * `firefox` - Firefox
 * * `safari` - Safari
 * * `edge` - Edge
 * * `opera` - Opera
 * @export
 */
export const BrowserEnum = {
    Chrome: 'chrome',
    Firefox: 'firefox',
    Safari: 'safari',
    Edge: 'edge',
    Opera: 'opera'
} as const;
export type BrowserEnum = typeof BrowserEnum[keyof typeof BrowserEnum];


export function instanceOfBrowserEnum(value: any): boolean {
    for (const key in BrowserEnum) {
        if (Object.prototype.hasOwnProperty.call(BrowserEnum, key)) {
            if (BrowserEnum[key as keyof typeof BrowserEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BrowserEnumFromJSON(json: any): BrowserEnum {
    return BrowserEnumFromJSONTyped(json, false);
}

export function BrowserEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): BrowserEnum {
    return json as BrowserEnum;
}

export function BrowserEnumToJSON(value?: BrowserEnum | null): any {
    return value as any;
}

