/* tslint:disable */
/* eslint-disable */
/**
 * Testplan API
 * API for managing test plans and related resources.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTestplansTestcasesTestresultsTestresultstepsRequestInner
 */
export interface CreateTestplansTestcasesTestresultsTestresultstepsRequestInner {
    /**
     * 
     * @type {number}
     * @memberof CreateTestplansTestcasesTestresultsTestresultstepsRequestInner
     */
    step?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreateTestplansTestcasesTestresultsTestresultstepsRequestInner
     */
    order: number;
    /**
     * 
     * @type {string}
     * @memberof CreateTestplansTestcasesTestresultsTestresultstepsRequestInner
     */
    action?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTestplansTestcasesTestresultsTestresultstepsRequestInner
     */
    expectedResult?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTestplansTestcasesTestresultsTestresultstepsRequestInner
     */
    status?: CreateTestplansTestcasesTestresultsTestresultstepsRequestInnerStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateTestplansTestcasesTestresultsTestresultstepsRequestInner
     */
    comment?: string;
}


/**
 * @export
 */
export const CreateTestplansTestcasesTestresultsTestresultstepsRequestInnerStatusEnum = {
    Pass: 'pass',
    Fail: 'fail',
    Skip: 'skip'
} as const;
export type CreateTestplansTestcasesTestresultsTestresultstepsRequestInnerStatusEnum = typeof CreateTestplansTestcasesTestresultsTestresultstepsRequestInnerStatusEnum[keyof typeof CreateTestplansTestcasesTestresultsTestresultstepsRequestInnerStatusEnum];


/**
 * Check if a given object implements the CreateTestplansTestcasesTestresultsTestresultstepsRequestInner interface.
 */
export function instanceOfCreateTestplansTestcasesTestresultsTestresultstepsRequestInner(value: object): value is CreateTestplansTestcasesTestresultsTestresultstepsRequestInner {
    if (!('order' in value) || value['order'] === undefined) return false;
    return true;
}

export function CreateTestplansTestcasesTestresultsTestresultstepsRequestInnerFromJSON(json: any): CreateTestplansTestcasesTestresultsTestresultstepsRequestInner {
    return CreateTestplansTestcasesTestresultsTestresultstepsRequestInnerFromJSONTyped(json, false);
}

export function CreateTestplansTestcasesTestresultsTestresultstepsRequestInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTestplansTestcasesTestresultsTestresultstepsRequestInner {
    if (json == null) {
        return json;
    }
    return {
        
        'step': json['step'] == null ? undefined : json['step'],
        'order': json['order'],
        'action': json['action'] == null ? undefined : json['action'],
        'expectedResult': json['expected_result'] == null ? undefined : json['expected_result'],
        'status': json['status'] == null ? undefined : json['status'],
        'comment': json['comment'] == null ? undefined : json['comment'],
    };
}

export function CreateTestplansTestcasesTestresultsTestresultstepsRequestInnerToJSON(value?: CreateTestplansTestcasesTestresultsTestresultstepsRequestInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'step': value['step'],
        'order': value['order'],
        'action': value['action'],
        'expected_result': value['expectedResult'],
        'status': value['status'],
        'comment': value['comment'],
    };
}

