/* tslint:disable */
/* eslint-disable */
/**
 * Testplan API
 * API for managing test plans and related resources.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTestplansTestcasesTeststepsRequestInner
 */
export interface CreateTestplansTestcasesTeststepsRequestInner {
    /**
     * 
     * @type {number}
     * @memberof CreateTestplansTestcasesTeststepsRequestInner
     */
    order: number;
    /**
     * 
     * @type {string}
     * @memberof CreateTestplansTestcasesTeststepsRequestInner
     */
    action?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTestplansTestcasesTeststepsRequestInner
     */
    expectedResult?: string;
}

/**
 * Check if a given object implements the CreateTestplansTestcasesTeststepsRequestInner interface.
 */
export function instanceOfCreateTestplansTestcasesTeststepsRequestInner(value: object): value is CreateTestplansTestcasesTeststepsRequestInner {
    if (!('order' in value) || value['order'] === undefined) return false;
    return true;
}

export function CreateTestplansTestcasesTeststepsRequestInnerFromJSON(json: any): CreateTestplansTestcasesTeststepsRequestInner {
    return CreateTestplansTestcasesTeststepsRequestInnerFromJSONTyped(json, false);
}

export function CreateTestplansTestcasesTeststepsRequestInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTestplansTestcasesTeststepsRequestInner {
    if (json == null) {
        return json;
    }
    return {
        
        'order': json['order'],
        'action': json['action'] == null ? undefined : json['action'],
        'expectedResult': json['expected_result'] == null ? undefined : json['expected_result'],
    };
}

export function CreateTestplansTestcasesTeststepsRequestInnerToJSON(value?: CreateTestplansTestcasesTeststepsRequestInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'order': value['order'],
        'action': value['action'],
        'expected_result': value['expectedResult'],
    };
}

