/* tslint:disable */
/* eslint-disable */
/**
 * Testplan API
 * API for managing test plans and related resources.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `windows10` - Windows 10
 * * `windows11` - Windows 11
 * * `macos` - macOS
 * * `linux` - Linux
 * * `android` - Android
 * * `ios` - iOS
 * @export
 */
export const OsEnum = {
    Windows10: 'windows10',
    Windows11: 'windows11',
    Macos: 'macos',
    Linux: 'linux',
    Android: 'android',
    Ios: 'ios'
} as const;
export type OsEnum = typeof OsEnum[keyof typeof OsEnum];


export function instanceOfOsEnum(value: any): boolean {
    for (const key in OsEnum) {
        if (Object.prototype.hasOwnProperty.call(OsEnum, key)) {
            if (OsEnum[key as keyof typeof OsEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OsEnumFromJSON(json: any): OsEnum {
    return OsEnumFromJSONTyped(json, false);
}

export function OsEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): OsEnum {
    return json as OsEnum;
}

export function OsEnumToJSON(value?: OsEnum | null): any {
    return value as any;
}

