/* tslint:disable */
/* eslint-disable */
/**
 * Testplan API
 * API for managing test plans and related resources.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TestCase } from './TestCase';
import {
    TestCaseFromJSON,
    TestCaseFromJSONTyped,
    TestCaseToJSON,
} from './TestCase';

/**
 * 
 * @export
 * @interface PaginatedTestCaseList
 */
export interface PaginatedTestCaseList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedTestCaseList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTestCaseList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTestCaseList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<TestCase>}
     * @memberof PaginatedTestCaseList
     */
    results: Array<TestCase>;
}

/**
 * Check if a given object implements the PaginatedTestCaseList interface.
 */
export function instanceOfPaginatedTestCaseList(value: object): value is PaginatedTestCaseList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedTestCaseListFromJSON(json: any): PaginatedTestCaseList {
    return PaginatedTestCaseListFromJSONTyped(json, false);
}

export function PaginatedTestCaseListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedTestCaseList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(TestCaseFromJSON)),
    };
}

export function PaginatedTestCaseListToJSON(value?: PaginatedTestCaseList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(TestCaseToJSON)),
    };
}

