/* tslint:disable */
/* eslint-disable */
/**
 * Testplan API
 * API for managing test plans and related resources.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TestPlan } from './TestPlan';
import {
    TestPlanFromJSON,
    TestPlanFromJSONTyped,
    TestPlanToJSON,
} from './TestPlan';

/**
 * 
 * @export
 * @interface PaginatedTestPlanList
 */
export interface PaginatedTestPlanList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedTestPlanList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTestPlanList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTestPlanList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<TestPlan>}
     * @memberof PaginatedTestPlanList
     */
    results: Array<TestPlan>;
}

/**
 * Check if a given object implements the PaginatedTestPlanList interface.
 */
export function instanceOfPaginatedTestPlanList(value: object): value is PaginatedTestPlanList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedTestPlanListFromJSON(json: any): PaginatedTestPlanList {
    return PaginatedTestPlanListFromJSONTyped(json, false);
}

export function PaginatedTestPlanListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedTestPlanList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(TestPlanFromJSON)),
    };
}

export function PaginatedTestPlanListToJSON(value?: PaginatedTestPlanList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(TestPlanToJSON)),
    };
}

