/* tslint:disable */
/* eslint-disable */
/**
 * Testplan API
 * API for managing test plans and related resources.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResultEnum } from './ResultEnum';
import {
    ResultEnumFromJSON,
    ResultEnumFromJSONTyped,
    ResultEnumToJSON,
} from './ResultEnum';

/**
 * 
 * @export
 * @interface PatchedTestResult
 */
export interface PatchedTestResult {
    /**
     * 
     * @type {number}
     * @memberof PatchedTestResult
     */
    readonly id?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedTestResult
     */
    _case?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedTestResult
     */
    readonly caseTitle?: string;
    /**
     * 
     * @type {ResultEnum}
     * @memberof PatchedTestResult
     */
    result?: ResultEnum;
    /**
     * 
     * @type {string}
     * @memberof PatchedTestResult
     */
    readonly _configuration?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedTestResult
     */
    tester?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedTestResult
     */
    readonly testerUsername?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedTestResult
     */
    readonly executedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedTestResult
     */
    readonly updatedAt?: Date;
}



/**
 * Check if a given object implements the PatchedTestResult interface.
 */
export function instanceOfPatchedTestResult(value: object): value is PatchedTestResult {
    return true;
}

export function PatchedTestResultFromJSON(json: any): PatchedTestResult {
    return PatchedTestResultFromJSONTyped(json, false);
}

export function PatchedTestResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedTestResult {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        '_case': json['case'] == null ? undefined : json['case'],
        'caseTitle': json['case_title'] == null ? undefined : json['case_title'],
        'result': json['result'] == null ? undefined : ResultEnumFromJSON(json['result']),
        '_configuration': json['configuration'] == null ? undefined : json['configuration'],
        'tester': json['tester'] == null ? undefined : json['tester'],
        'testerUsername': json['tester_username'] == null ? undefined : json['tester_username'],
        'executedAt': json['executed_at'] == null ? undefined : (new Date(json['executed_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function PatchedTestResultToJSON(value?: Omit<PatchedTestResult, 'id'|'case_title'|'configuration'|'tester_username'|'executed_at'|'updated_at'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'case': value['_case'],
        'result': ResultEnumToJSON(value['result']),
        'tester': value['tester'],
    };
}

