/* tslint:disable */
/* eslint-disable */
/**
 * Testplan API
 * API for managing test plans and related resources.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `pass` - Pass
 * * `fail` - Fail
 * * `in_progress` - In Progress
 * @export
 */
export const ResultEnum = {
    Pass: 'pass',
    Fail: 'fail',
    InProgress: 'in_progress'
} as const;
export type ResultEnum = typeof ResultEnum[keyof typeof ResultEnum];


export function instanceOfResultEnum(value: any): boolean {
    for (const key in ResultEnum) {
        if (Object.prototype.hasOwnProperty.call(ResultEnum, key)) {
            if (ResultEnum[key as keyof typeof ResultEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ResultEnumFromJSON(json: any): ResultEnum {
    return ResultEnumFromJSONTyped(json, false);
}

export function ResultEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultEnum {
    return json as ResultEnum;
}

export function ResultEnumToJSON(value?: ResultEnum | null): any {
    return value as any;
}

