/* tslint:disable */
/* eslint-disable */
/**
 * Testplan API
 * API for managing test plans and related resources.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RetrieveTestplansTestcasesTestresultsTestresultstepattachmentsDownload404Response
 */
export interface RetrieveTestplansTestcasesTestresultsTestresultstepattachmentsDownload404Response {
    /**
     * 
     * @type {string}
     * @memberof RetrieveTestplansTestcasesTestresultsTestresultstepattachmentsDownload404Response
     */
    detail?: string;
}

/**
 * Check if a given object implements the RetrieveTestplansTestcasesTestresultsTestresultstepattachmentsDownload404Response interface.
 */
export function instanceOfRetrieveTestplansTestcasesTestresultsTestresultstepattachmentsDownload404Response(value: object): value is RetrieveTestplansTestcasesTestresultsTestresultstepattachmentsDownload404Response {
    return true;
}

export function RetrieveTestplansTestcasesTestresultsTestresultstepattachmentsDownload404ResponseFromJSON(json: any): RetrieveTestplansTestcasesTestresultsTestresultstepattachmentsDownload404Response {
    return RetrieveTestplansTestcasesTestresultsTestresultstepattachmentsDownload404ResponseFromJSONTyped(json, false);
}

export function RetrieveTestplansTestcasesTestresultsTestresultstepattachmentsDownload404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetrieveTestplansTestcasesTestresultsTestresultstepattachmentsDownload404Response {
    if (json == null) {
        return json;
    }
    return {
        
        'detail': json['detail'] == null ? undefined : json['detail'],
    };
}

export function RetrieveTestplansTestcasesTestresultsTestresultstepattachmentsDownload404ResponseToJSON(value?: RetrieveTestplansTestcasesTestresultsTestresultstepattachmentsDownload404Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'detail': value['detail'],
    };
}

