/* tslint:disable */
/* eslint-disable */
/**
 * Testplan API
 * API for managing test plans and related resources.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TestCaseStatusEnum } from './TestCaseStatusEnum';
import {
    TestCaseStatusEnumFromJSON,
    TestCaseStatusEnumFromJSONTyped,
    TestCaseStatusEnumToJSON,
} from './TestCaseStatusEnum';

/**
 * 
 * @export
 * @interface TestCase
 */
export interface TestCase {
    /**
     * 
     * @type {number}
     * @memberof TestCase
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof TestCase
     */
    readonly executedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof TestCase
     */
    readonly latestResult: string;
    /**
     * 
     * @type {string}
     * @memberof TestCase
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof TestCase
     */
    description?: string;
    /**
     * 
     * @type {TestCaseStatusEnum}
     * @memberof TestCase
     */
    status?: TestCaseStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof TestCase
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof TestCase
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof TestCase
     */
    plan: number;
}



/**
 * Check if a given object implements the TestCase interface.
 */
export function instanceOfTestCase(value: object): value is TestCase {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('executedAt' in value) || value['executedAt'] === undefined) return false;
    if (!('latestResult' in value) || value['latestResult'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('plan' in value) || value['plan'] === undefined) return false;
    return true;
}

export function TestCaseFromJSON(json: any): TestCase {
    return TestCaseFromJSONTyped(json, false);
}

export function TestCaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestCase {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'executedAt': (new Date(json['executed_at'])),
        'latestResult': json['latest_result'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'status': json['status'] == null ? undefined : TestCaseStatusEnumFromJSON(json['status']),
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'plan': json['plan'],
    };
}

export function TestCaseToJSON(value?: Omit<TestCase, 'id'|'executed_at'|'latest_result'|'created_at'|'updated_at'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'description': value['description'],
        'status': TestCaseStatusEnumToJSON(value['status']),
        'plan': value['plan'],
    };
}

