/* tslint:disable */
/* eslint-disable */
/**
 * Testplan API
 * API for managing test plans and related resources.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `not_started` - Not Started
 * * `in_progress` - In Progress
 * * `completed` - Completed
 * @export
 */
export const TestPlanStatusEnum = {
    NotStarted: 'not_started',
    InProgress: 'in_progress',
    Completed: 'completed'
} as const;
export type TestPlanStatusEnum = typeof TestPlanStatusEnum[keyof typeof TestPlanStatusEnum];


export function instanceOfTestPlanStatusEnum(value: any): boolean {
    for (const key in TestPlanStatusEnum) {
        if (Object.prototype.hasOwnProperty.call(TestPlanStatusEnum, key)) {
            if (TestPlanStatusEnum[key as keyof typeof TestPlanStatusEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TestPlanStatusEnumFromJSON(json: any): TestPlanStatusEnum {
    return TestPlanStatusEnumFromJSONTyped(json, false);
}

export function TestPlanStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestPlanStatusEnum {
    return json as TestPlanStatusEnum;
}

export function TestPlanStatusEnumToJSON(value?: TestPlanStatusEnum | null): any {
    return value as any;
}

