/* tslint:disable */
/* eslint-disable */
/**
 * Testplan API
 * API for managing test plans and related resources.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TestPlanCreate
 */
export interface TestPlanCreate {
    /**
     * 
     * @type {string}
     * @memberof TestPlanCreate
     */
    title: string;
}

/**
 * Check if a given object implements the TestPlanCreate interface.
 */
export function instanceOfTestPlanCreate(value: object): value is TestPlanCreate {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function TestPlanCreateFromJSON(json: any): TestPlanCreate {
    return TestPlanCreateFromJSONTyped(json, false);
}

export function TestPlanCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestPlanCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
    };
}

export function TestPlanCreateToJSON(value?: TestPlanCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
    };
}

