/* tslint:disable */
/* eslint-disable */
/**
 * Testplan API
 * API for managing test plans and related resources.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TestStepAttachment
 */
export interface TestStepAttachment {
    /**
     * 
     * @type {number}
     * @memberof TestStepAttachment
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof TestStepAttachment
     */
    step: number;
    /**
     * 
     * @type {string}
     * @memberof TestStepAttachment
     */
    file: string;
}

/**
 * Check if a given object implements the TestStepAttachment interface.
 */
export function instanceOfTestStepAttachment(value: object): value is TestStepAttachment {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('step' in value) || value['step'] === undefined) return false;
    if (!('file' in value) || value['file'] === undefined) return false;
    return true;
}

export function TestStepAttachmentFromJSON(json: any): TestStepAttachment {
    return TestStepAttachmentFromJSONTyped(json, false);
}

export function TestStepAttachmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestStepAttachment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'step': json['step'],
        'file': json['file'],
    };
}

export function TestStepAttachmentToJSON(value?: Omit<TestStepAttachment, 'id'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'step': value['step'],
        'file': value['file'],
    };
}

