/* tslint:disable */
/* eslint-disable */
/**
 * Testplan API
 * API for managing test plans and related resources.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `design` - Design
 * * `ready` - Ready
 * * `closed` - Closed
 * @export
 */
export const TestCaseStatusEnum = {
    Design: 'design',
    Ready: 'ready',
    Closed: 'closed'
} as const;
export type TestCaseStatusEnum = typeof TestCaseStatusEnum[keyof typeof TestCaseStatusEnum];


export function instanceOfTestCaseStatusEnum(value: any): boolean {
    for (const key in TestCaseStatusEnum) {
        if (Object.prototype.hasOwnProperty.call(TestCaseStatusEnum, key)) {
            if (TestCaseStatusEnum[key as keyof typeof TestCaseStatusEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TestCaseStatusEnumFromJSON(json: any): TestCaseStatusEnum {
    return TestCaseStatusEnumFromJSONTyped(json, false);
}

export function TestCaseStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestCaseStatusEnum {
    return json as TestCaseStatusEnum;
}

export function TestCaseStatusEnumToJSON(value?: TestCaseStatusEnum | null): any {
    return value as any;
}

