/* tslint:disable */
/* eslint-disable */
/**
 * Testplan API
 * API for managing test plans and related resources.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TestResultStepAttachment
 */
export interface TestResultStepAttachment {
    /**
     * 
     * @type {number}
     * @memberof TestResultStepAttachment
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof TestResultStepAttachment
     */
    resultStep: number;
    /**
     * 
     * @type {string}
     * @memberof TestResultStepAttachment
     */
    file: string;
}

/**
 * Check if a given object implements the TestResultStepAttachment interface.
 */
export function instanceOfTestResultStepAttachment(value: object): value is TestResultStepAttachment {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('resultStep' in value) || value['resultStep'] === undefined) return false;
    if (!('file' in value) || value['file'] === undefined) return false;
    return true;
}

export function TestResultStepAttachmentFromJSON(json: any): TestResultStepAttachment {
    return TestResultStepAttachmentFromJSONTyped(json, false);
}

export function TestResultStepAttachmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestResultStepAttachment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'resultStep': json['result_step'],
        'file': json['file'],
    };
}

export function TestResultStepAttachmentToJSON(value?: Omit<TestResultStepAttachment, 'id'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'result_step': value['resultStep'],
        'file': value['file'],
    };
}

