/* tslint:disable */
/* eslint-disable */
/**
 * Testplan API
 * API for managing test plans and related resources.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `pass` - Pass
 * * `fail` - Fail
 * * `skip` - Skip
 * @export
 */
export const TestResultStepStatusEnum = {
    Pass: 'pass',
    Fail: 'fail',
    Skip: 'skip'
} as const;
export type TestResultStepStatusEnum = typeof TestResultStepStatusEnum[keyof typeof TestResultStepStatusEnum];


export function instanceOfTestResultStepStatusEnum(value: any): boolean {
    for (const key in TestResultStepStatusEnum) {
        if (Object.prototype.hasOwnProperty.call(TestResultStepStatusEnum, key)) {
            if (TestResultStepStatusEnum[key as keyof typeof TestResultStepStatusEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TestResultStepStatusEnumFromJSON(json: any): TestResultStepStatusEnum {
    return TestResultStepStatusEnumFromJSONTyped(json, false);
}

export function TestResultStepStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestResultStepStatusEnum {
    return json as TestResultStepStatusEnum;
}

export function TestResultStepStatusEnumToJSON(value?: TestResultStepStatusEnum | null): any {
    return value as any;
}

