/* tslint:disable */
/* eslint-disable */
/**
 * Testplan API
 * API for managing test plans and related resources.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TestStep
 */
export interface TestStep {
    /**
     * 
     * @type {number}
     * @memberof TestStep
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof TestStep
     */
    _case: number;
    /**
     * 
     * @type {number}
     * @memberof TestStep
     */
    order: number;
    /**
     * 
     * @type {string}
     * @memberof TestStep
     */
    action?: string;
    /**
     * 
     * @type {string}
     * @memberof TestStep
     */
    expectedResult?: string;
}

/**
 * Check if a given object implements the TestStep interface.
 */
export function instanceOfTestStep(value: object): value is TestStep {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('_case' in value) || value['_case'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    return true;
}

export function TestStepFromJSON(json: any): TestStep {
    return TestStepFromJSONTyped(json, false);
}

export function TestStepFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestStep {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        '_case': json['case'],
        'order': json['order'],
        'action': json['action'] == null ? undefined : json['action'],
        'expectedResult': json['expected_result'] == null ? undefined : json['expected_result'],
    };
}

export function TestStepToJSON(value?: Omit<TestStep, 'id'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'case': value['_case'],
        'order': value['order'],
        'action': value['action'],
        'expected_result': value['expectedResult'],
    };
}

