openapi: 3.0.3
info:
  title: Testplan API
  version: 1.0.0
  description: API for managing test plans and related resources.
paths:
  /api/v1/testplans/:
    get:
      operationId: listTestplans
      parameters:
      - in: query
        name: name
        schema:
          type: string
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - in: query
        name: status
        schema:
          type: string
          enum:
          - completed
          - in_progress
          - not_started
        description: |-
          * `not_started` - Not Started
          * `in_progress` - In Progress
          * `completed` - Completed
      tags:
      - testplans
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedTestPlanList'
          description: ''
    post:
      operationId: createTestplans
      tags:
      - testplans
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestPlanCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TestPlanCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TestPlanCreate'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestPlanCreate'
          description: ''
  /api/v1/testplans/{id}/:
    get:
      operationId: retrieveTestplans
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this test plan.
        required: true
      tags:
      - testplans
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestPlan'
          description: ''
    put:
      operationId: updateTestplans
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this test plan.
        required: true
      tags:
      - testplans
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestPlan'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TestPlan'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TestPlan'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestPlan'
          description: ''
    patch:
      operationId: partialUpdateTestplans
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this test plan.
        required: true
      tags:
      - testplans
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedTestPlan'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedTestPlan'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedTestPlan'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestPlan'
          description: ''
    delete:
      operationId: destroyTestplans
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this test plan.
        required: true
      tags:
      - testplans
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    PaginatedTestPlanList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/TestPlan'
    PatchedTestPlan:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        description:
          type: string
        status:
          $ref: '#/components/schemas/StatusEnum'
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
    StatusEnum:
      enum:
      - not_started
      - in_progress
      - completed
      type: string
      description: |-
        * `not_started` - Not Started
        * `in_progress` - In Progress
        * `completed` - Completed
    TestPlan:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        description:
          type: string
        status:
          $ref: '#/components/schemas/StatusEnum'
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - id
      - name
      - updated_at
    TestPlanCreate:
      type: object
      properties:
        name:
          type: string
          maxLength: 255
      required:
      - name
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
