name: Client CI

on:
  push:
    branches: [ main, develop ]
    paths: [ 'client/**' ]
  pull_request:
    branches: [ main, develop ]
    paths: [ 'client/**' ]
  workflow_call:

jobs:
  client-ci:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: client/package-lock.json
        
    - name: Install dependencies
      working-directory: ./client
      run: npm ci

    - name: Lint
      working-directory: ./client
      run: npm run lint
      
    - name: Style lint
      working-directory: ./client
      run: npm run lint:style

    - name: Build
      working-directory: ./client
      run: npm run build
      
    - name: Run tests
      working-directory: ./client
      run: npm run test:unit -- --run
